-- All IITs
INSERT INTO "Institute" (name, short_name, affiliation, logo_url, website_url, mail_slug) VALUES
('Indian Institute of Technology Bombay', 'IITB', 'IIT', 'http://localhost:3000/iitb', 'https://www.iitb.ac.in', 'iitb.ac.in'),
('Indian Institute of Technology Delhi', 'IITD', 'IIT', 'http://localhost:3000/iitd', 'https://www.iitd.ac.in', 'iitd.ac.in'),
('Indian Institute of Technology Kanpur', 'IITK', 'IIT', 'http://localhost:3000/iitk', 'https://www.iitk.ac.in', 'iitk.ac.in'),
('Indian Institute of Technology Madras', 'IITM', 'IIT', 'http://localhost:3000/iitm', 'https://www.iitm.ac.in', 'iitm.ac.in'),
('Indian Institute of Technology Kharagpur', 'IITKGP', 'IIT', 'http://localhost:3000/iitkgp', 'https://www.iitkgp.ac.in', 'iitkgp.ac.in'),
('Indian Institute of Technology Roorkee', 'IITR', 'IIT', 'http://localhost:3000/iitr', 'https://www.iitr.ac.in', 'iitr.ac.in'),
('Indian Institute of Technology Guwahati', 'IITG', 'IIT', 'http://localhost:3000/iitg', 'https://www.iitg.ac.in', 'iitg.ac.in'),
('Indian Institute of Technology Hyderabad', 'IITH', 'IIT', 'http://localhost:3000/iith', 'https://www.iith.ac.in', 'iith.ac.in'),
('Indian Institute of Technology Bhubaneswar', 'IITBBS', 'IIT', 'http://localhost:3000/iitbbs', 'https://www.iitbbs.ac.in', 'iitbbs.ac.in'),
('Indian Institute of Technology Gandhinagar', 'IITGN', 'IIT', 'http://localhost:3000/iitgn', 'https://www.iitgn.ac.in', 'iitgn.ac.in'),
('Indian Institute of Technology Indore', 'IITI', 'IIT', 'http://localhost:3000/iiti', 'https://www.iiti.ac.in', 'iiti.ac.in'),
('Indian Institute of Technology Jodhpur', 'IITJ', 'IIT', 'http://localhost:3000/iitj', 'https://www.iitj.ac.in', 'iitj.ac.in'),
('Indian Institute of Technology Mandi', 'IITMandi', 'IIT', 'http://localhost:3000/iitmandi', 'https://www.iitmandi.ac.in', 'iitmandi.ac.in'),
('Indian Institute of Technology Patna', 'IITP', 'IIT', 'http://localhost:3000/iitp', 'https://www.iitp.ac.in', 'iitp.ac.in'),
('Indian Institute of Technology Ropar', 'IITRPR', 'IIT', 'http://localhost:3000/iitrpr', 'https://www.iitrpr.ac.in', 'iitrpr.ac.in'),
('Indian Institute of Technology Tirupati', 'IITT', 'IIT', 'http://localhost:3000/iitt', 'https://www.iittp.ac.in', 'iittp.ac.in'),
('Indian Institute of Technology Palakkad', 'IITPKD', 'IIT', 'http://localhost:3000/iitpkd', 'https://www.iitpkd.ac.in', 'iitpkd.ac.in'),
('Indian Institute of Technology Dhanbad', 'IITISM', 'IIT', 'http://localhost:3000/iitism', 'https://www.iitism.ac.in', 'iitism.ac.in'),
('Indian Institute of Technology Bhilai', 'IITBH', 'IIT', 'http://localhost:3000/iitbh', 'https://www.iitbhilai.ac.in', 'iitbhilai.ac.in'),
('Indian Institute of Technology Goa', 'IITGOA', 'IIT', 'http://localhost:3000/iitgoa', 'https://www.iitgoa.ac.in', 'iitgoa.ac.in'),
('Indian Institute of Technology Jammu', 'IITJammu', 'IIT', 'http://localhost:3000/iitjammu', 'https://www.iitjammu.ac.in', 'iitjammu.ac.in'),
('Indian Institute of Technology Dharwad', 'IITDH', 'IIT', 'http://localhost:3000/iitdh', 'https://www.iitdh.ac.in', 'iitdh.ac.in');

-- All NITs
INSERT INTO "Institute" (name, short_name, affiliation, logo_url, website_url, mail_slug) VALUES
('National Institute of Technology Tiruchirappalli', 'NITT', 'NIT', 'http://localhost:3000/nitt', 'https://www.nitt.edu', 'nitt.edu'),
('National Institute of Technology Warangal', 'NITW', 'NIT', 'http://localhost:3000/nitw', 'https://www.nitw.ac.in', 'nitw.ac.in'),
('National Institute of Technology Surathkal', 'NITS', 'NIT', 'http://localhost:3000/nits', 'https://www.nitk.ac.in', 'nitk.ac.in'),
('National Institute of Technology Rourkela', 'NITR', 'NIT', 'http://localhost:3000/nitr', 'https://www.nitrkl.ac.in', 'nitrkl.ac.in'),
('National Institute of Technology Kurukshetra', 'NITK', 'NIT', 'http://localhost:3000/nitk', 'https://www.nitkkr.ac.in', 'nitkkr.ac.in'),
('National Institute of Technology Calicut', 'NITC', 'NIT', 'http://localhost:3000/nitc', 'https://www.nitc.ac.in', 'nitc.ac.in'),
('National Institute of Technology Jaipur', 'MNIT', 'NIT', 'http://localhost:3000/mnit', 'https://www.mnit.ac.in', 'mnit.ac.in'),
('National Institute of Technology Allahabad', 'MNNIT', 'NIT', 'http://localhost:3000/mnnit', 'https://www.mnnit.ac.in', 'mnnit.ac.in'),
('National Institute of Technology Durgapur', 'NITDGP', 'NIT', 'http://localhost:3000/nitdgp', 'https://www.nitdgp.ac.in', 'nitdgp.ac.in'),
('National Institute of Technology Jamshedpur', 'NITJSR', 'NIT', 'http://localhost:3000/nitjsr', 'https://www.nitjsr.ac.in', 'nitjsr.ac.in'),
('National Institute of Technology Patna', 'NITP', 'NIT', 'http://localhost:3000/nitp', 'https://www.nitp.ac.in', 'nitp.ac.in'),
('National Institute of Technology Raipur', 'NITRR', 'NIT', 'http://localhost:3000/nitrr', 'https://www.nitrr.ac.in', 'nitrr.ac.in'),
('National Institute of Technology Agartala', 'NITA', 'NIT', 'http://localhost:3000/nita', 'https://www.nita.ac.in', 'nita.ac.in'),
('National Institute of Technology Silchar', 'NITSIL', 'NIT', 'http://localhost:3000/nitsil', 'https://www.nits.ac.in', 'nits.ac.in'),
('National Institute of Technology Meghalaya', 'NITMGH', 'NIT', 'http://localhost:3000/nitmgh', 'https://www.nitm.ac.in', 'nitm.ac.in'),
('National Institute of Technology Arunachal Pradesh', 'NITAP', 'NIT', 'http://localhost:3000/nitap', 'https://www.nitap.ac.in', 'nitap.ac.in'),
('National Institute of Technology Nagaland', 'NITN', 'NIT', 'http://localhost:3000/nitn', 'https://www.nitnagaland.ac.in', 'nitnagaland.ac.in'),
('National Institute of Technology Manipur', 'NITMN', 'NIT', 'http://localhost:3000/nitmn', 'https://www.nitmanipur.ac.in', 'nitmanipur.ac.in'),
('National Institute of Technology Mizoram', 'NITMZ', 'NIT', 'http://localhost:3000/nitmz', 'https://www.nitmz.ac.in', 'nitmz.ac.in'),
('National Institute of Technology Sikkim', 'NITSKM', 'NIT', 'http://localhost:3000/nitskm', 'https://www.nitsikkim.ac.in', 'nitsikkim.ac.in'),
('National Institute of Technology Puducherry', 'NITPY', 'NIT', 'http://localhost:3000/nitpy', 'https://www.nitpy.ac.in', 'nitpy.ac.in'),
('National Institute of Technology Goa', 'NITGOA', 'NIT', 'http://localhost:3000/nitgoa', 'https://www.nitgoa.ac.in', 'nitgoa.ac.in'),
('National Institute of Technology Uttarakhand', 'NITUK', 'NIT', 'http://localhost:3000/nituk', 'https://www.nituk.ac.in', 'nituk.ac.in'),
('National Institute of Technology Delhi', 'NITD', 'NIT', 'http://localhost:3000/nitd', 'https://www.nitdelhi.ac.in', 'nitdelhi.ac.in'),
('Dr. B. R. Ambedkar National Institute of Technology Jalandhar', 'NITJ', 'NIT', 'http://localhost:3000/nitj', 'https://www.nitj.ac.in', 'nitj.ac.in'),
('Maulana Azad National Institute of Technology Bhopal', 'MANIT', 'NIT', 'http://localhost:3000/manit', 'https://www.manit.ac.in', 'manit.ac.in'),
('Sardar Vallabhbhai National Institute of Technology Surat', 'SVNIT', 'NIT', 'http://localhost:3000/svnit', 'https://www.svnit.ac.in', 'svnit.ac.in'),
('Visvesvaraya National Institute of Technology Nagpur', 'VNIT', 'NIT', 'http://localhost:3000/vnit', 'https://www.vnit.ac.in', 'vnit.ac.in');

-- All IIITs
INSERT INTO "Institute" (name, short_name, affiliation, logo_url, website_url, mail_slug) VALUES
('Indian Institute of Information Technology Allahabad', 'IIITA', 'IIIT', 'http://localhost:3000/iiita', 'https://www.iiita.ac.in', 'iiita.ac.in'),
('Indian Institute of Information Technology Gwalior', 'IIITGWL', 'IIIT', 'http://localhost:3000/iiitgwl', 'https://www.iiitm.ac.in', 'iiitm.ac.in'),
('Indian Institute of Information Technology Jabalpur', 'IIITDMJ', 'IIIT', 'http://localhost:3000/iiitdmj', 'https://www.iiitdmj.ac.in', 'iiitdmj.ac.in'),
('Indian Institute of Information Technology Kancheepuram', 'IIITDMK', 'IIIT', 'http://localhost:3000/iiitdmk', 'https://www.iiitdm.ac.in', 'iiitdm.ac.in'),
('Indian Institute of Information Technology Kurnool', 'IIITKUR', 'IIIT', 'http://localhost:3000/iiitkur', 'https://www.iiitk.ac.in', 'iiitk.ac.in'),
('Indian Institute of Information Technology Kota', 'IIITKOTA', 'IIIT', 'http://localhost:3000/iiitkota', 'https://www.iiitkota.ac.in', 'iiitkota.ac.in'),
('Indian Institute of Information Technology Pune', 'IIITP', 'IIIT', 'http://localhost:3000/iiitp', 'https://www.iiitp.ac.in', 'iiitp.ac.in'),
('Indian Institute of Information Technology Lucknow', 'IIITL', 'IIIT', 'http://localhost:3000/iiitl', 'https://www.iiitl.ac.in', 'iiitl.ac.in'),
('Indian Institute of Information Technology Una', 'IIITU', 'IIIT', 'http://localhost:3000/iiitu', 'https://www.iiitu.ac.in', 'iiitu.ac.in'),
('Indian Institute of Information Technology Kottayam', 'IIITK', 'IIIT', 'http://localhost:3000/iiitk', 'https://www.iiitkottayam.ac.in', 'iiitkottayam.ac.in'),
('Indian Institute of Information Technology Sri City', 'IIITS', 'IIIT', 'http://localhost:3000/iiits', 'https://www.iiits.ac.in', 'iiits.ac.in'),
('Indian Institute of Information Technology Vadodara', 'IIITV', 'IIIT', 'http://localhost:3000/iiitv', 'https://www.iiitvadodara.ac.in', 'iiitvadodara.ac.in'),
('Indian Institute of Information Technology Ranchi', 'IIITR', 'IIIT', 'http://localhost:3000/iiitr', 'https://www.iiitranchi.ac.in', 'iiitranchi.ac.in'),
('Indian Institute of Information Technology Guwahati', 'IIITG', 'IIIT', 'http://localhost:3000/iiitg', 'https://www.iiitg.ac.in', 'iiitg.ac.in'),
('Indian Institute of Information Technology Dharwad', 'IIITDH', 'IIIT', 'http://localhost:3000/iiitdh', 'https://www.iiitd.ac.in', 'iiitd.ac.in'),
('Indian Institute of Information Technology Bhagalpur', 'IIITBG', 'IIIT', 'http://localhost:3000/iiitbg', 'https://www.iiitbh.ac.in', 'iiitbh.ac.in'),
('Indian Institute of Information Technology Nagpur', 'IIITN', 'IIIT', 'http://localhost:3000/iiitn', 'https://www.iiitn.ac.in', 'iiitn.ac.in'),
('Indian Institute of Information Technology Raichur', 'IIITRCR', 'IIIT', 'http://localhost:3000/iiitrcr', 'https://www.iiitr.ac.in', 'iiitr.ac.in'),
('Indian Institute of Information Technology Tiruchirappalli', 'IIITT', 'IIIT', 'http://localhost:3000/iiitt', 'https://www.iiitt.ac.in', 'iiitt.ac.in'),
('Indian Institute of Information Technology Agartala', 'IIITAG', 'IIIT', 'http://localhost:3000/iiitag', 'https://www.iiitagartala.ac.in', 'iiitagartala.ac.in'),
('Indian Institute of Information Technology Surat', 'IIITSRT', 'IIIT', 'http://localhost:3000/iiitsrt', 'https://www.iiitsurat.ac.in', 'iiitsurat.ac.in'),
('Indian Institute of Information Technology Bhopal', 'IIITBHOP', 'IIIT', 'http://localhost:3000/iiitbhop', 'https://www.iiitbhopal.ac.in', 'iiitbhopal.ac.in'),
('Indian Institute of Information Technology Manipur', 'IIITMNPR', 'IIIT', 'http://localhost:3000/iiitmnpr', 'https://www.iiitmanipur.ac.in', 'iiitmanipur.ac.in'),
('Indian Institute of Information Technology Sonipat', 'IIITSNPT', 'IIIT', 'http://localhost:3000/iiitsnpt', 'https://www.iiitsonipat.ac.in', 'iiitsonipat.ac.in'),
('Indian Institute of Information Technology Aurangabad', 'IIITAUR', 'IIIT', 'http://localhost:3000/iiitaur', 'https://www.iiitaurangabad.ac.in', 'iiitaurangabad.ac.in');
